/**
 * Client-side PDF generation for a product analysis using jsPDF.
 * Produces a real, branded .pdf (forest-green + gold) — selectable text,
 * organized sections, page breaks — not a browser print dialog.
 */
import type { AnalysisView } from "@/modules/analysis";

type RGB = [number, number, number];

const C = {
  green: [11, 34, 24] as RGB,
  green800: [21, 57, 43] as RGB,
  gold: [184, 138, 42] as RGB, // slightly darker gold for print contrast
  ink: [16, 36, 27] as RGB,
  body: [75, 90, 82] as RGB,
  muted: [139, 150, 144] as RGB,
  white: [255, 255, 255] as RGB,
  red: [214, 72, 60] as RGB,
  greenPos: [47, 143, 78] as RGB,
  orange: [232, 116, 59] as RGB,
  blue: [46, 134, 216] as RGB,
};

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "product";
}

export async function exportAnalysisPdf(analysis: AnalysisView, productName: string): Promise<void> {
  const result = analysis.result;
  if (!result) return;

  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 44;
  const contentW = pageW - margin * 2;
  let y = 0;

  const setFill = (c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
  const setText = (c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
  const setDraw = (c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);

  function ensure(space: number) {
    if (y + space > pageH - 60) {
      doc.addPage();
      y = margin + 8;
    }
  }

  function heading(title: string, color: RGB) {
    ensure(40);
    setText(color);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(title.toUpperCase(), margin, y);
    y += 7;
    setDraw(color);
    doc.setLineWidth(2);
    doc.line(margin, y, margin + 46, y);
    y += 18;
  }

  function paragraph(text: string, color: RGB = C.body, size = 10.5) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    setText(color);
    const lines = doc.splitTextToSize(text, contentW);
    ensure(lines.length * 14 + 4);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 6;
  }

  function bullets(items: string[], color: RGB) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    for (const item of items) {
      const lines = doc.splitTextToSize(item, contentW - 16);
      ensure(lines.length * 14 + 4);
      setFill(color);
      doc.circle(margin + 3, y - 3.5, 1.6, "F");
      setText(C.body);
      doc.text(lines, margin + 14, y);
      y += lines.length * 14 + 4;
    }
    y += 10;
  }

  // ── Header band ──
  setFill(C.green);
  doc.rect(0, 0, pageW, 96, "F");
  setText(C.gold);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("GROWTHOS  ·  PRODUCT ANALYSIS", margin, 40);
  setText(C.white);
  doc.setFontSize(24);
  const titleLines = doc.splitTextToSize(productName, contentW);
  doc.text(titleLines[0] ?? productName, margin, 70);
  y = 128;

  // ── Customer Avatar ──
  heading("Customer Avatar", C.gold);
  paragraph(result.customerAvatar.summary, C.ink, 11);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  setText(C.muted);
  ensure(16);
  doc.text("DEMOGRAPHICS", margin, y);
  y += 14;
  bullets(result.customerAvatar.demographics, C.gold);
  setText(C.muted);
  doc.setFont("helvetica", "bold");
  ensure(16);
  doc.text("PSYCHOGRAPHICS", margin, y);
  y += 14;
  bullets(result.customerAvatar.psychographics, C.gold);

  // ── List sections ──
  const sections: { title: string; items: string[]; color: RGB }[] = [
    { title: "Pain Points", items: result.painPoints, color: C.red },
    { title: "Desires", items: result.desires, color: C.greenPos },
    { title: "Objections", items: result.objections, color: C.orange },
    { title: "Buying Motivations", items: result.buyingMotivations, color: C.blue },
    { title: "Emotional Triggers", items: result.emotionalTriggers, color: C.gold },
    { title: "Logical Triggers", items: result.logicalTriggers, color: C.green800 },
  ];
  for (const s of sections) {
    heading(s.title, s.color);
    bullets(s.items, s.color);
  }

  // ── USP ──
  heading("USP Analysis", C.gold);
  paragraph(`Differentiation: ${result.uspAnalysis.differentiation}`, C.ink);
  bullets(result.uspAnalysis.uniqueSellingPoints, C.gold);

  // ── Footers (page numbers + provenance) ──
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setText(C.muted);
    const footer = `Generated by GrowthOS${analysis.model ? ` · ${analysis.model}` : ""}`;
    doc.text(footer, margin, pageH - 28);
    doc.text(`${i} / ${pages}`, pageW - margin, pageH - 28, { align: "right" });
  }

  doc.save(`${slug(productName)}-analysis.pdf`);
}
