/**
 * Client-side branded PDF for a generated landing page. Walks the version's
 * sections in order and renders real, selectable copy with page breaks.
 */
import {
  SECTION_LABEL,
  type HeroContent,
  type ProblemContent,
  type BenefitsContent,
  type FeaturesContent,
  type ComparisonContent,
  type SocialProofContent,
  type TestimonialsContent,
  type GuaranteeContent,
  type FaqContent,
  type CtaContent,
  type FormContent,
  type GalleryContent,
} from "@/modules/landing/application/landing-schema";
import type { PageVersionView, SectionView } from "@/modules/landing/application/dto";

type RGB = [number, number, number];
const C = {
  green: [11, 34, 24] as RGB,
  gold: [184, 138, 42] as RGB,
  ink: [16, 36, 27] as RGB,
  body: [75, 90, 82] as RGB,
  muted: [139, 150, 144] as RGB,
  white: [255, 255, 255] as RGB,
};

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "product";
}

export async function exportLandingPdf(version: PageVersionView, productName: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 44;
  const contentW = pageW - margin * 2;
  let y = 0;

  const setFill = (c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
  const setText = (c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
  const setDraw = (c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);
  const ensure = (space: number) => {
    if (y + space > pageH - 56) {
      doc.addPage();
      y = margin + 8;
    }
  };

  function heading(title: string) {
    ensure(40);
    setText(C.gold);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(title.toUpperCase(), margin, y);
    y += 8;
    setDraw(C.gold);
    doc.setLineWidth(2);
    doc.line(margin, y, margin + 50, y);
    y += 18;
  }
  function subheading(title: string) {
    ensure(24);
    setText(C.ink);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    doc.text(doc.splitTextToSize(title, contentW), margin, y);
    y += 16;
  }
  function paragraph(text: string) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    setText(C.body);
    const lines = doc.splitTextToSize(text, contentW);
    ensure(lines.length * 14 + 6);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 6;
  }
  function bullets(items: string[]) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    for (const item of items) {
      const lines = doc.splitTextToSize(item, contentW - 16);
      ensure(lines.length * 14 + 4);
      setFill(C.gold);
      doc.circle(margin + 3, y - 3.5, 1.6, "F");
      setText(C.body);
      doc.text(lines, margin + 14, y);
      y += lines.length * 14 + 4;
    }
    y += 6;
  }
  function pair(title: string, desc: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    setText(C.ink);
    let lines = doc.splitTextToSize(title, contentW);
    ensure(lines.length * 14 + 24);
    doc.text(lines, margin, y);
    y += lines.length * 13 + 2;
    doc.setFont("helvetica", "normal");
    setText(C.body);
    lines = doc.splitTextToSize(desc, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 13 + 8;
  }

  // Header band
  setFill(C.green);
  doc.rect(0, 0, pageW, 96, "F");
  setText(C.gold);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(`GROWTHOS  ·  LANDING PAGE  ·  ${version.framework}`, margin, 40);
  setText(C.white);
  doc.setFontSize(22);
  doc.text(doc.splitTextToSize(productName, contentW)[0] ?? productName, margin, 70);
  y = 128;

  if (version.rationale) {
    paragraph(`Framework: ${version.framework} — ${version.rationale}`);
  }

  for (const section of version.sections) {
    renderSection(section, { heading, subheading, paragraph, bullets, pair });
  }

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setText(C.muted);
    doc.text(
      `Generated by GrowthOS · v${version.version}${version.model ? ` · ${version.model}` : ""}`,
      margin,
      pageH - 28,
    );
    doc.text(`${i} / ${pages}`, pageW - margin, pageH - 28, { align: "right" });
  }

  doc.save(`${slug(productName)}-landing-page-v${version.version}.pdf`);
}

interface Writers {
  heading: (t: string) => void;
  subheading: (t: string) => void;
  paragraph: (t: string) => void;
  bullets: (items: string[]) => void;
  pair: (title: string, desc: string) => void;
}

function renderSection(section: SectionView, w: Writers) {
  w.heading(SECTION_LABEL[section.type]);
  switch (section.type) {
    case "HERO": {
      const c = section.content as HeroContent;
      w.subheading(c.headline);
      w.paragraph(c.subheadline);
      if (c.supportingPoints?.length) w.bullets(c.supportingPoints);
      w.paragraph(`CTA: ${c.ctaLabel}`);
      break;
    }
    case "GALLERY": {
      const c = section.content as GalleryContent;
      w.paragraph(`${c.images?.length ?? 0} product image(s) — see the page preview or HTML export.`);
      break;
    }
    case "PROBLEM": {
      const c = section.content as ProblemContent;
      w.subheading(c.headline);
      w.paragraph(c.body);
      w.bullets(c.painPoints);
      break;
    }
    case "BENEFITS": {
      const c = section.content as BenefitsContent;
      w.subheading(c.headline);
      for (const it of c.items) w.pair(it.title, it.description);
      break;
    }
    case "FEATURES": {
      const c = section.content as FeaturesContent;
      w.subheading(c.headline);
      for (const it of c.items) w.pair(it.title, it.description);
      break;
    }
    case "COMPARISON": {
      const c = section.content as ComparisonContent;
      w.subheading(c.headline);
      w.bullets(
        c.rows.map((r) => `${r.point} — ${c.productLabel}: ${r.hasProduct ? "✓" : "✕"} / ${c.alternativeLabel}: ${r.hasAlternative ? "✓" : "✕"}`),
      );
      break;
    }
    case "SOCIAL_PROOF": {
      const c = section.content as SocialProofContent;
      w.subheading(c.headline);
      if (c.stats?.length) w.bullets(c.stats.map((s) => `${s.value} — ${s.label}`));
      if (c.highlights?.length) w.bullets(c.highlights);
      break;
    }
    case "GUARANTEE": {
      const c = section.content as GuaranteeContent;
      w.subheading(`${c.headline} [${c.badge}]`);
      w.paragraph(c.body);
      break;
    }
    case "TESTIMONIALS": {
      const c = section.content as TestimonialsContent;
      w.subheading(c.headline);
      for (const t of c.items) w.pair(`${t.author}${t.role ? ` · ${t.role}` : ""}`, `“${t.quote}”`);
      break;
    }
    case "FAQ": {
      const c = section.content as FaqContent;
      w.subheading(c.headline);
      for (const f of c.items) w.pair(f.question, f.answer);
      break;
    }
    case "CTA": {
      const c = section.content as CtaContent;
      w.subheading(c.headline);
      w.paragraph(c.subheadline);
      w.paragraph(`Button: ${c.buttonLabel}${c.urgency ? ` · ${c.urgency}` : ""}`);
      break;
    }
    case "FORM": {
      const c = section.content as FormContent;
      w.subheading(c.headline);
      w.paragraph(c.subheadline);
      w.bullets(["First name", "Last name", "Phone number", "Email address"]);
      w.paragraph(`Button: ${c.buttonLabel}${c.consent ? ` · ${c.consent}` : ""}`);
      break;
    }
  }
}
